export const turkish = [
    'Sözcükte Anlam',
    'Söz Gruplarında Anlam',
    'Deyimler ve Atasözleri',
    'Cümlede Anlam',
    'Söz Sanatları',
    'Metin Türleri',
    'Fiilimsiler',
    'Cümlenin Ögeleri',
    'Cümle Türleri',
    'Yazım Kuralları',
    'Noktalama İşaretleri',
    'Parçada Anlam',
    'Fiilde Çatı',
    'Sözel Mantık / Görsel Okuma',
    'Anlatım Bozuklukları'
]
export const math = [
    'Çarpanlar ve Katlar',
    'Üslü İfadeler',
    'Kareköklü İfadeler',
    'Veri Analizi',
    'Basit Olayların Olma Olasılığı',
    'Cebirsel İfadeler ve Özdeşlikler',
    'Doğrusal Denklemler',
    'Eşitsizlikler',
    'Üçgenler',
    'Eşlik ve Benzerlik',
    'Dönüşüm Geometrisi',
    'Geometrik Cisimler'
]

export const science = [
    'Mevsimler ve İklim / Dünya ve Evren',
    'Mevsimlerin Oluşumu',
    'İklim ve Hava Hareketleri',
    'DNA ve Genetik Kod',
    'Kalıtım',
    'Mutasyon ve Modifikasyon',
    'Adaptasyon (Çevreye Uyum)',
    'Biyoteknoloji',
    'Basınç',
    'Periyodik Sistem',
    'Fiziksel ve Kimyasal Değişimler',
    'Kimyasal Tepkimeler',
    'Asitler ve Bazlar',
    'Maddenin Isı ile Etkileşimi',
    'Türkiye’de Kimya Endüstrisi',
    'Basit Makineler',
    'Besin Zinciri ve Enerji Akışı',
    'Enerji Dönüşümleri',
    'Madde Döngüleri ve Çevre Sorunları',
    'Sürdürülebilir Kalkınma',
    'Elektrik Yükleri ve Elektriklenme',
    'Elektrik Yüklü Cisimler',
    'Elektrik Enerjisinin Dönüşümü',
]

export const english = [
    'Friendship',
    'Teen Life',
    'In the Kitchen',
    'On the Phone',
    'The Internet',
    'Adventures',
    'Tourism',
    'Chores',
    'Science',
    'Natural Forces'
]

export const religion = [
    'Kader ve Kaza İnancı',
    'İnsanın İradesi ve Kader',
    'Kaderle İlgili Kavramlar,',
    'Bir Peygamber Tanıyorum: Hz. Musa (a.s.)',
    'Bir Ayet Tanıyorum: Ayet el-Kürsi ve Anlamı',
    'İslam’ın Paylaşma ve Yardımlaşmaya Verdiği Önem',
    'Zekât ve Sadaka İbadeti',
    'Zekât ve Sadakanın Bireysel ve Toplumsal Faydaları',
    'Bir Peygamber Tanıyorum: Hz. Şuayb (a.s.)',
    'Bir Sure Tanıyorum: Maûn Suresi ve Anlamı',
    'Din, Birey ve Toplum',
    'Dinin Temel Gayesi',
    'Bir Peygamber Tanıyorum: Hz. Yusuf (a.s.)',
    'Bir Sure Tanıyorum: Asr Suresi ve Anlamı',
    'Hz.Muhammed’in Örnekliği',
    'Muhammed’in (s.a.v) Doğruluğu ve Güvenilir Kişiliği',
    'Muhammed’in (s.a.v) Merhametli ve Affedici Oluşu',
    'Muhammed’in (s.a.v) İstişareye Önem Vermesi',
    'Muhammed’in Davasındaki Cesaret ve Kararlılığı',
    'Muhammed’in Hakkı Gözetmedeki Hassasiyeti',
    'Muhammed’in (s.a.v) İnsanlara Değer Vermesi',
    'Bir Sure Tanıyorum: Kureyş Suresi ve Anlamı',
    'Kuran-ı Kerim ve Özellikleri',
    'İslam Dininin Temel Kaynakları',
    'Kur’an-ı Kerim’in Ana Konuları',
    'Kur’an-ı Kerim’in Temel Özellikleri',
    'Bir Peygamber Tanıyorum: Hz. Nuh (a.s.)'
]

export const history = [
    'Yüzyıl Başlarında Osmanlı Devleti',
    'Mustafa Kemal Okulda',
    'Gençlik Döneminde Atatürk’ü Etkileyen Önemli Kişiler ve Olaylar',
    'Cepheden Cepheye Mustafa Kemal',
    'Bir Dünya Savaşı',
    'Dünya Savaşında Osmanlı Devleti',
    'Geldikleri Gibi Giderler',
    'Kuvay-ı Milliye ve Cemiyetler',
    'Ve Milli Mücadele Başlıyor',
    'Egemenlik Milletindir',
    'Büyük Millet Meclisi İsyanlara Karşı',
    'Barış Antlaşması Mı Ölüm Fermanı Mı?',
    'İlk Zaferimiz Destanlaşan Direnişimiz',
    'İstiklâl Milletindir. Savaşa Rağmen Eğitim Kongresi',
    'Anadolu İnsanının Büyük Fedakârlığı - Diriliş Destanı: Sakarya Hayat Veren Zafer, Savaşa Son Veren Belge',
    'Zafer Ve Bağımsızlığın Tescili: Lozan Barış Antlaşması',
    'Sanat Ve Edebiyat Eserlerinde Kurtuluş Savaşımız',
    'Atatürkçülük ve Çağdaşlaşan Türkiye',
    'Çağdaşlaşmanın Temeli: Atatürk İlkeleri',
    'Siyasi Alanda Yapılan İnkılâplar',
    'Hukuk Alanında Yapılan İnkılâplar',
    'Eğitim Ve Kültür Alanında Yapılan İnkılâplar',
    'Toplumsal Alanında Yapılan İnkılâplar',
    'Ekonomi Alanında Yapılan İnkılâplar',
    'Sağlık Alanında Yapılan İnkılâplar',
    'Cumhuriyetimizle Bir Milletiz',
    'Çok Partili Demokratik Yaşam',
    'Rejime Yönelik Tehditler',
    'Türk Dış Politikası',
    'Atatürk Dönemi Türk Dış Politikası Gelişmeleri',
    'Hatay Türkiye’ye Katılıyor',
    'Atatürk’ün Son Günleri Ve Ölümü',
    'Atatürk’ün Eserleri',
    'Dünya Savaşı ve Türkiye',
    'Demokrasi Yolunda Türkiye'
]